adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
adam_weight_decay: 0.01
allow_tf32: false
center_crop: false
checkpointing_steps: 800
checkpoints_total_limit: null
class_data_dir: /home/mike/python_files/deep_generative_models/deep_generative_models_saved/HW4/reg_dataset
class_labels_conditioning: null
class_prompt: 'a photo of man face '
dataloader_num_workers: 0
enable_xformers_memory_efficient_attention: false
gradient_accumulation_steps: 1
gradient_checkpointing: false
hub_model_id: null
hub_token: null
instance_data_dir: /home/mike/python_files/deep_generative_models/deep_generative_models_saved/HW4/birme-512x512
instance_prompt: a photo of sks man face
learning_rate: 8.0e-05
local_rank: -1
logging_dir: /home/mike/python_files/deep_generative_models/deep_generative_models_saved/HW4/db_generation_lora_rank_4/log_dir
lr_num_cycles: 1
lr_power: 1.0
lr_scheduler: constant
lr_warmup_steps: 0
max_grad_norm: 1.0
max_train_steps: 800
mixed_precision: 'no'
num_class_images: 500
num_train_epochs: 2
num_validation_images: 4
output_dir: /home/mike/python_files/deep_generative_models/deep_generative_models_saved/HW4/db_generation_lora_rank_4
pre_compute_text_embeddings: false
pretrained_model_name_or_path: /home/mike/python_files/deep_generative_models/deep_generative_models_saved/HW4/stable-diffusion-weights/CyberRealistic
prior_generation_precision: null
prior_loss_weight: 1.0
push_to_hub: false
rank: 4
report_to: tensorboard
resolution: 512
resume_from_checkpoint: null
revision: null
sample_batch_size: 4
scale_lr: false
seed: null
text_encoder_use_attention_mask: false
tokenizer_max_length: null
tokenizer_name: null
train_batch_size: 1
train_text_encoder: true
use_8bit_adam: true
validation_epochs: 50
validation_prompt: null
variant: null
with_prior_preservation: true
